CREATE TABLE pm.program (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    program_code VARCHAR(255) NOT NULL DEFAULT pm.generate_program_code,
    name VARCHAR(255) NOT NULL,   
    description TEXT,
    start_date TIMESTAMPTZ,
    end_date TIMESTAMPTZ,
    customer_id UUID,
    program_manager_id UUID,
    supply_chain_manager_id UUID,
    buyer_id UUID,
    status VARCHAR(255),
    goals TEXT,
    budget DECIMAL(18, 2),
    actual_spend DECIMAL(18, 2),
	is_active BOOLEAN NOT NULL DEFAULT TRUE,
	created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(255) NOT NULL,
    updated_at TIMESTAMPTZ,
    updated_by VARCHAR(255),
    deleted_at TIMESTAMPTZ,
    deleted_by VARCHAR(255),
    FOREIGN KEY(customer_id) REFERENCES application.customer(id) ON DELETE SET NULL,
    FOREIGN KEY(program_manager_id) REFERENCES application.user(id) ON DELETE SET NULL,
    FOREIGN KEY(supply_chain_manager_id) REFERENCES application.user(id) ON DELETE SET NULL,
    FOREIGN KEY(buyer_id) REFERENCES application.user(id) ON DELETE SET NULL
);