-- Table: mes.part
-- DROP TABLE IF EXISTS mes.part;
 
CREATE TABLE mes.part (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    part_number_suffix VARCHAR(255) NOT NULL,
    version CHAR(2) CHECK (version ~ '^[0-9]{2}$') NOT NULL DEFAULT '01',
    part_number VARCHAR(255) GENERATED ALWAYS AS (part_number_suffix || '-' || version) STORED UNIQUE NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT, 
    part_type_id UUID NOT NULL,
    weight FLOAT NOT NULL DEFAULT 0,  
    unit_of_measure_id UUID,
    make_buy INT NOT NULL,
    eco_id UUID,
    status VARCHAR(20) CHECK (status IN ('Draft', 'Release', 'Obsolete', 'Archived')) DEFAULT 'Draft',
    number VARCHAR(255),
    unit_price DECIMAL(18,2),
    manufacturing_part_number TEXT UNIQUE,
    manufacturer_name VARCHAR(255),
    material VARCHAR(255),
    trl INT,
    space_qualified BOOLEAN,
    item_type VARCHAR(255),    
    reference_number VARCHAR(255),
    has_bom BOOLEAN NOT NULL DEFAULT FALSE,
    country_of_origin_id UUID,
    short_description TEXT,
    subsystem_id UUID,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_serial_number_required BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(255) NOT NULL,
    updated_at TIMESTAMPTZ,
    updated_by VARCHAR(255),
    deleted_at TIMESTAMPTZ,
    deleted_by VARCHAR(255),
    FOREIGN KEY (eco_id) REFERENCES mes.eco(id) ON DELETE SET NULL,
    FOREIGN KEY (part_type_id) REFERENCES mes.part_type(id) ON DELETE SET NULL,
    FOREIGN KEY (unit_of_measure_id) REFERENCES mes.unit_of_measure(id) ON DELETE SET NULL,
    FOREIGN KEY (country_of_origin_id) REFERENCES common.country(id) ON DELETE SET NULL,
    FOREIGN KEY (subsystem_id) REFERENCES mes.subsystem(id) ON DELETE SET NULL,
    CONSTRAINT chk_manufacturer_details_required CHECK (make_buy = 1 AND ((item_type::text = ANY (ARRAY['Goods'::character varying, 'Services'::character varying]::text[])) OR manufacturing_part_number IS NOT NULL AND TRIM(BOTH FROM manufacturing_part_number) <> ''::text AND manufacturer_name IS NOT NULL AND TRIM(BOTH FROM manufacturer_name) <> ''::text) OR make_buy = 0),
	UNIQUE(manufacturing_part_number, deleted_at)
);