#!/usr/bin/env node
// SpaceLinx permission catalog code-generator.
// Single source of truth: permissions.catalog.json
// Emits: C# constants, TS PERMISSIONS object, and an idempotent SQL seed.
// Usage: node tools/permission-catalog/generate.mjs   (run from repo root or anywhere)
// Zero external dependencies.

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, '..', '..');
const catalogPath = resolve(here, 'permissions.catalog.json');

const OUT = {
  cs:  resolve(repoRoot, 'src/SpaceLinx.Api/SpaceLinx.Api/Security/Permissions.Generated.cs'),
  ts:  resolve(repoRoot, 'src/spacelinx-mes/src/constants/permissions.generated.ts'),
  sql: resolve(repoRoot, 'database/migrations/seed/permissions.seed.sql'),
};

const catalog = JSON.parse(readFileSync(catalogPath, 'utf8'));
const perms = [...catalog.permissions].sort((a, b) => a.key.localeCompare(b.key));

// ---------- helpers ----------
const camelWord = (w) => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase();
function toPascal(seg) {
  if (seg.includes('_')) return seg.split('_').map(camelWord).join('');
  if (/[a-z]/.test(seg)) return seg.charAt(0).toUpperCase() + seg.slice(1); // mixed case e.g. ApprovalsConfig
  return camelWord(seg);                                                    // ALL CAPS single word
}
const sqlEsc = (s) => s.replace(/'/g, "''");

// build a nested tree of segments -> {__leaf?: key, children}
function buildTree() {
  const root = {};
  for (const p of perms) {
    const segs = p.key.split('.');
    let node = root;
    segs.forEach((seg, i) => {
      node.children ??= {};
      node.children[seg] ??= {};
      node = node.children[seg];
      if (i === segs.length - 1) node.__leaf = p.key;
    });
  }
  return root;
}

// ---------- C# ----------
function emitCs() {
  const tree = buildTree();
  const lines = [];
  lines.push('// <auto-generated>');
  lines.push('//   Generated by tools/permission-catalog/generate.mjs from permissions.catalog.json.');
  lines.push('//   DO NOT EDIT BY HAND. Edit the catalog JSON and regenerate.');
  lines.push('// </auto-generated>');
  lines.push('#nullable enable');
  lines.push('namespace SpaceLinx.Api.Security;');
  lines.push('');
  lines.push('/// <summary>Strongly-typed SpaceLinx permission keys (single source of truth).</summary>');
  lines.push('public static class Permissions');
  lines.push('{');

  // C# forbids a nested member sharing its enclosing type's name; disambiguate against ancestors.
  const uniq = (name, ancestors, suffix) => {
    let n = name;
    while (ancestors.includes(n)) n += suffix;
    return n;
  };
  const walk = (node, indent, ancestors) => {
    const pad = '    '.repeat(indent);
    const children = node.children ?? {};
    for (const seg of Object.keys(children).sort()) {
      const child = children[seg];
      const hasChildren = child.children && Object.keys(child.children).length > 0;
      if (child.__leaf && !hasChildren) {
        lines.push(`${pad}public const string ${uniq(toPascal(seg), ancestors, 'Value')} = "${child.__leaf}";`);
      } else {
        const cn = uniq(toPascal(seg), ancestors, 'Group');
        lines.push(`${pad}public static class ${cn}`);
        lines.push(`${pad}{`);
        if (child.__leaf) lines.push(`${'    '.repeat(indent + 1)}public const string _Self = "${child.__leaf}";`);
        walk(child, indent + 1, [...ancestors, cn]);
        lines.push(`${pad}}`);
      }
    }
  };
  walk(tree, 1, ['Permissions']);

  lines.push('');
  lines.push('    /// <summary>All permission keys (for seeding / validation).</summary>');
  lines.push('    public static readonly string[] All =');
  lines.push('    [');
  for (const p of perms) lines.push(`        "${p.key}",`);
  lines.push('    ];');
  lines.push('}');
  return lines.join('\n') + '\n';
}

// ---------- TS ----------
function emitTs() {
  const tree = buildTree();
  const lines = [];
  lines.push('// AUTO-GENERATED by tools/permission-catalog/generate.mjs from permissions.catalog.json.');
  lines.push('// DO NOT EDIT BY HAND. Edit the catalog JSON and regenerate.');
  lines.push('');
  const render = (node, indent) => {
    const pad = '  '.repeat(indent);
    const children = node.children ?? {};
    const out = [];
    for (const seg of Object.keys(children).sort()) {
      const child = children[seg];
      const hasChildren = child.children && Object.keys(child.children).length > 0;
      const prop = /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(seg) ? seg : JSON.stringify(seg);
      if (child.__leaf && !hasChildren) {
        out.push(`${pad}${prop}: "${child.__leaf}",`);
      } else {
        const inner = render(child, indent + 1);
        const self = child.__leaf ? `${'  '.repeat(indent + 1)}_SELF: "${child.__leaf}",\n` : '';
        out.push(`${pad}${prop}: {\n${self}${inner}\n${pad}},`);
      }
    }
    return out.join('\n');
  };
  lines.push('export const PERMISSIONS = {');
  lines.push(render(tree, 1));
  lines.push('} as const;');
  lines.push('');
  lines.push('export type PermissionKey =');
  lines.push(perms.map((p) => `  | "${p.key}"`).join('\n') + ';');
  lines.push('');
  lines.push('export const ALL_PERMISSIONS: PermissionKey[] = [');
  lines.push(perms.map((p) => `  "${p.key}",`).join('\n'));
  lines.push('];');
  return lines.join('\n') + '\n';
}

// ---------- SQL seed (idempotent) ----------
function emitSql() {
  const L = [];
  L.push('-- AUTO-GENERATED by tools/permission-catalog/generate.mjs from permissions.catalog.json.');
  L.push('-- Idempotent permission seed. Safe to re-run. Review before applying (T1.2).');
  L.push('-- NOTE: application.permission.category_name currently stores the human description');
  L.push('--       (matching existing rows). Category is derived from the key prefix in code.');
  L.push('BEGIN;');
  L.push('');
  L.push('-- 1) Upsert all catalog permissions. Existing rows (by unique name) are left untouched.');
  L.push('INSERT INTO application.permission (name, category_name, created_by)');
  L.push('VALUES');
  const values = perms.map(
    (p) => `  ('${sqlEsc(p.key)}', '${sqlEsc(p.description)}', 'system-seed')`
  );
  L.push(values.join(',\n') + '');
  L.push('ON CONFLICT (name) DO NOTHING;');
  L.push('');
  L.push('-- 2) Fix legacy typo alias: VENDORS.DOC.DELETE -> VENDORS.DOCUMENTS.DELETE');
  L.push("--    (canonical row inserted above; migrate any role grants, then retire the typo row)");
  L.push("UPDATE application.role_permission");
  L.push("   SET permission = 'VENDORS.DOCUMENTS.DELETE', updated_at = now(), updated_by = 'system-seed'");
  L.push("   WHERE permission = 'VENDORS.DOC.DELETE' AND deleted_at IS NULL;");
  L.push('');
  L.push("UPDATE application.permission");
  L.push("   SET deleted_at = now(), deleted_by = 'system-seed', is_active = false");
  L.push("   WHERE name = 'VENDORS.DOC.DELETE' AND deleted_at IS NULL;");
  L.push('');
  L.push('COMMIT;');
  return L.join('\n') + '\n';
}

// ---------- write ----------
for (const [k, file] of Object.entries(OUT)) {
  mkdirSync(dirname(file), { recursive: true });
  const content = k === 'cs' ? emitCs() : k === 'ts' ? emitTs() : emitSql();
  writeFileSync(file, content);
  console.log(`wrote ${file.replace(repoRoot + '/', '')}`);
}
const seedCount = perms.filter((p) => !p.inDb).length;
console.log(`\ncatalog: ${perms.length} permissions, ${new Set(perms.map((p) => p.category)).size} categories`);
console.log(`seed inserts ${seedCount} new permissions (existing left untouched via ON CONFLICT)`);
