// <auto-generated>
//   Generated by tools/permission-catalog/generate.mjs from permissions.catalog.json.
//   DO NOT EDIT BY HAND. Edit the catalog JSON and regenerate.
// </auto-generated>
#nullable enable
namespace SpaceLinx.Api.Security;

/// <summary>Strongly-typed SpaceLinx permission keys (single source of truth).</summary>
public static class Permissions
{
    public static class Additionalrecipients
    {
        public const string Delete = "ADDITIONALRECIPIENTS.DELETE";
        public const string Modify = "ADDITIONALRECIPIENTS.MODIFY";
        public const string View = "ADDITIONALRECIPIENTS.VIEW";
    }
    public static class Assemblylocations
    {
        public const string Delete = "ASSEMBLYLOCATIONS.DELETE";
        public const string Modify = "ASSEMBLYLOCATIONS.MODIFY";
        public const string View = "ASSEMBLYLOCATIONS.VIEW";
    }
    public static class Audit
    {
        public static class View
        {
            public const string _Self = "AUDIT.VIEW";
            public const string Regulated = "AUDIT.VIEW.REGULATED";
        }
    }
    public static class ApprovalsConfig
    {
        public const string Create = "ApprovalsConfig.CREATE";
        public const string Delete = "ApprovalsConfig.DELETE";
        public const string Modify = "ApprovalsConfig.MODIFY";
        public const string View = "ApprovalsConfig.VIEW";
    }
    public static class Binmanagement
    {
        public const string Delete = "BINMANAGEMENT.DELETE";
        public const string Modify = "BINMANAGEMENT.MODIFY";
        public const string View = "BINMANAGEMENT.VIEW";
    }
    public static class Bom
    {
        public const string View = "BOM.VIEW";
    }
    public static class Bulkupload
    {
        public const string Modify = "BULKUPLOAD.MODIFY";
        public const string View = "BULKUPLOAD.VIEW";
    }
    public static class Companies
    {
        public const string Delete = "COMPANIES.DELETE";
        public static class Documents
        {
            public const string Delete = "COMPANIES.DOCUMENTS.DELETE";
            public const string Modify = "COMPANIES.DOCUMENTS.MODIFY";
            public const string View = "COMPANIES.DOCUMENTS.VIEW";
        }
        public const string Modify = "COMPANIES.MODIFY";
        public const string View = "COMPANIES.VIEW";
    }
    public static class Contacts
    {
        public const string Delete = "CONTACTS.DELETE";
        public const string Modify = "CONTACTS.MODIFY";
        public const string View = "CONTACTS.VIEW";
    }
    public static class Customers
    {
        public const string Delete = "CUSTOMERS.DELETE";
        public const string Modify = "CUSTOMERS.MODIFY";
        public const string View = "CUSTOMERS.VIEW";
    }
    public static class Dashboards
    {
        public const string Configure = "DASHBOARDS.CONFIGURE";
        public const string View = "DASHBOARDS.VIEW";
    }
    public static class Departments
    {
        public const string Delete = "DEPARTMENTS.DELETE";
        public const string Modify = "DEPARTMENTS.MODIFY";
        public const string View = "DEPARTMENTS.VIEW";
    }
    public static class Eco
    {
        public const string Approver = "ECO.APPROVER";
        public const string Delete = "ECO.DELETE";
        public static class Documents
        {
            public const string Delete = "ECO.DOCUMENTS.DELETE";
            public const string Modify = "ECO.DOCUMENTS.MODIFY";
            public const string View = "ECO.DOCUMENTS.VIEW";
        }
        public static class Effectedparts
        {
            public const string Delete = "ECO.EFFECTEDPARTS.DELETE";
            public const string Modify = "ECO.EFFECTEDPARTS.MODIFY";
            public const string View = "ECO.EFFECTEDPARTS.VIEW";
        }
        public const string Modify = "ECO.MODIFY";
        public const string View = "ECO.VIEW";
    }
    public static class Emaillogs
    {
        public const string View = "EMAILLOGS.VIEW";
    }
    public static class Emailtemplates
    {
        public const string Delete = "EMAILTEMPLATES.DELETE";
        public const string Modify = "EMAILTEMPLATES.MODIFY";
        public const string View = "EMAILTEMPLATES.VIEW";
    }
    public static class Features
    {
        public const string Delete = "FEATURES.DELETE";
        public const string Modify = "FEATURES.MODIFY";
        public const string View = "FEATURES.VIEW";
    }
    public static class Gantt
    {
        public const string Modify = "GANTT.MODIFY";
        public const string View = "GANTT.VIEW";
    }
    public static class Goods
    {
        public const string Delete = "GOODS.DELETE";
        public const string Modify = "GOODS.MODIFY";
        public static class Transactions
        {
            public const string View = "GOODS.TRANSACTIONS.VIEW";
        }
        public const string View = "GOODS.VIEW";
    }
    public static class Goodsreceipts
    {
        public const string Approver = "GOODSRECEIPTS.APPROVER";
        public const string Delete = "GOODSRECEIPTS.DELETE";
        public static class Documents
        {
            public const string Delete = "GOODSRECEIPTS.DOCUMENTS.DELETE";
            public const string Modify = "GOODSRECEIPTS.DOCUMENTS.MODIFY";
            public const string View = "GOODSRECEIPTS.DOCUMENTS.VIEW";
        }
        public const string Modify = "GOODSRECEIPTS.MODIFY";
        public const string View = "GOODSRECEIPTS.VIEW";
    }
    public static class Guides
    {
        public const string Clone = "GUIDES.CLONE";
        public const string Delete = "GUIDES.DELETE";
        public const string Modify = "GUIDES.MODIFY";
        public const string Print = "GUIDES.PRINT";
        public const string Publish = "GUIDES.PUBLISH";
        public const string View = "GUIDES.VIEW";
    }
    public static class Issues
    {
        public const string Delete = "ISSUES.DELETE";
        public const string Modify = "ISSUES.MODIFY";
        public const string View = "ISSUES.VIEW";
    }
    public static class Kanban
    {
        public const string Configure = "KANBAN.CONFIGURE";
        public const string Modify = "KANBAN.MODIFY";
        public const string View = "KANBAN.VIEW";
    }
    public static class Locations
    {
        public const string Delete = "LOCATIONS.DELETE";
        public const string Modify = "LOCATIONS.MODIFY";
        public const string View = "LOCATIONS.VIEW";
    }
    public static class Machines
    {
        public const string Delete = "MACHINES.DELETE";
        public const string Modify = "MACHINES.MODIFY";
        public const string View = "MACHINES.VIEW";
    }
    public static class Materialkits
    {
        public const string Assignworkorder = "MATERIALKITS.ASSIGNWORKORDER";
        public const string Delete = "MATERIALKITS.DELETE";
        public const string Modify = "MATERIALKITS.MODIFY";
        public const string View = "MATERIALKITS.VIEW";
    }
    public static class News
    {
        public const string Delete = "NEWS.DELETE";
        public const string Modify = "NEWS.MODIFY";
        public const string View = "NEWS.VIEW";
    }
    public static class Organization
    {
        public static class Address
        {
            public const string Delete = "ORGANIZATION.ADDRESS.DELETE";
            public const string Modify = "ORGANIZATION.ADDRESS.MODIFY";
            public const string View = "ORGANIZATION.ADDRESS.VIEW";
        }
        public const string Delete = "ORGANIZATION.DELETE";
        public const string Modify = "ORGANIZATION.MODIFY";
        public const string View = "ORGANIZATION.VIEW";
    }
    public static class Partlevels
    {
        public const string Delete = "PARTLEVELS.DELETE";
        public const string Modify = "PARTLEVELS.MODIFY";
        public const string View = "PARTLEVELS.VIEW";
    }
    public static class Partners
    {
        public const string Delete = "PARTNERS.DELETE";
        public static class Documents
        {
            public const string Delete = "PARTNERS.DOCUMENTS.DELETE";
            public const string Modify = "PARTNERS.DOCUMENTS.MODIFY";
            public const string View = "PARTNERS.DOCUMENTS.VIEW";
        }
        public const string Modify = "PARTNERS.MODIFY";
        public const string View = "PARTNERS.VIEW";
    }
    public static class Parts
    {
        public static class Bom
        {
            public const string Clone = "PARTS.BOM.CLONE";
            public const string Delete = "PARTS.BOM.DELETE";
            public const string Modify = "PARTS.BOM.MODIFY";
            public const string View = "PARTS.BOM.VIEW";
        }
        public const string Delete = "PARTS.DELETE";
        public static class Documents
        {
            public const string Delete = "PARTS.DOCUMENTS.DELETE";
            public const string Modify = "PARTS.DOCUMENTS.MODIFY";
            public const string View = "PARTS.DOCUMENTS.VIEW";
        }
        public static class Inventory
        {
            public const string Modify = "PARTS.INVENTORY.MODIFY";
            public const string Price = "PARTS.INVENTORY.PRICE";
            public const string View = "PARTS.INVENTORY.VIEW";
        }
        public const string Modify = "PARTS.MODIFY";
        public const string Revise = "PARTS.REVISE";
        public static class Transactions
        {
            public const string View = "PARTS.TRANSACTIONS.VIEW";
        }
        public const string View = "PARTS.VIEW";
        public static class Whereused
        {
            public const string View = "PARTS.WHEREUSED.VIEW";
        }
    }
    public static class Parttypecategories
    {
        public const string Delete = "PARTTYPECATEGORIES.DELETE";
        public const string Modify = "PARTTYPECATEGORIES.MODIFY";
        public const string View = "PARTTYPECATEGORIES.VIEW";
    }
    public static class Parttypes
    {
        public const string Delete = "PARTTYPES.DELETE";
        public const string Modify = "PARTTYPES.MODIFY";
        public const string View = "PARTTYPES.VIEW";
    }
    public static class Paymentterms
    {
        public const string Delete = "PAYMENTTERMS.DELETE";
        public const string Modify = "PAYMENTTERMS.MODIFY";
        public const string View = "PAYMENTTERMS.VIEW";
    }
    public static class PermissionsGroup
    {
        public const string Delete = "PERMISSIONS.DELETE";
        public const string Modify = "PERMISSIONS.MODIFY";
        public const string View = "PERMISSIONS.VIEW";
    }
    public static class Products
    {
        public static class Bom
        {
            public const string Delete = "PRODUCTS.BOM.DELETE";
            public const string Modify = "PRODUCTS.BOM.MODIFY";
            public const string View = "PRODUCTS.BOM.VIEW";
        }
        public const string Delete = "PRODUCTS.DELETE";
        public const string Modify = "PRODUCTS.MODIFY";
        public const string View = "PRODUCTS.VIEW";
        public static class Workorders
        {
            public const string View = "PRODUCTS.WORKORDERS.VIEW";
        }
    }
    public static class Programs
    {
        public const string Delete = "PROGRAMS.DELETE";
        public static class Linkedprojects
        {
            public const string View = "PROGRAMS.LINKEDPROJECTS.VIEW";
        }
        public static class Milestones
        {
            public const string View = "PROGRAMS.MILESTONES.VIEW";
        }
        public const string Modify = "PROGRAMS.MODIFY";
        public const string View = "PROGRAMS.VIEW";
    }
    public static class Projects
    {
        public const string Delete = "PROJECTS.DELETE";
        public const string Modify = "PROJECTS.MODIFY";
        public const string View = "PROJECTS.VIEW";
    }
    public static class Purchaseorders
    {
        public const string Approver = "PURCHASEORDERS.APPROVER";
        public const string Delete = "PURCHASEORDERS.DELETE";
        public static class Documents
        {
            public const string Delete = "PURCHASEORDERS.DOCUMENTS.DELETE";
            public const string Modify = "PURCHASEORDERS.DOCUMENTS.MODIFY";
            public const string View = "PURCHASEORDERS.DOCUMENTS.VIEW";
        }
        public const string Modify = "PURCHASEORDERS.MODIFY";
        public const string Print = "PURCHASEORDERS.PRINT";
        public const string View = "PURCHASEORDERS.VIEW";
        public const string ViewAllDepartments = "PURCHASEORDERS.VIEW_ALL_DEPARTMENTS";
    }
    public static class Qualitycheck
    {
        public const string Delete = "QUALITYCHECK.DELETE";
        public const string Modify = "QUALITYCHECK.MODIFY";
        public const string View = "QUALITYCHECK.VIEW";
    }
    public static class Qualitychecks
    {
        public const string Approver = "QUALITYCHECKS.APPROVER";
        public const string Delete = "QUALITYCHECKS.DELETE";
        public static class Documents
        {
            public const string Delete = "QUALITYCHECKS.DOCUMENTS.DELETE";
            public const string Modify = "QUALITYCHECKS.DOCUMENTS.MODIFY";
            public const string View = "QUALITYCHECKS.DOCUMENTS.VIEW";
        }
        public const string Modify = "QUALITYCHECKS.MODIFY";
        public const string View = "QUALITYCHECKS.VIEW";
    }
    public static class Reports
    {
        public static class Bomconsolidated
        {
            public const string View = "REPORTS.BOMCONSOLIDATED.VIEW";
        }
        public const string Delete = "REPORTS.DELETE";
        public const string Modify = "REPORTS.MODIFY";
        public static class Stockreport
        {
            public const string View = "REPORTS.STOCKREPORT.VIEW";
        }
        public const string View = "REPORTS.VIEW";
    }
    public static class Requisitions
    {
        public const string Approver = "REQUISITIONS.APPROVER";
        public const string Delete = "REQUISITIONS.DELETE";
        public static class Documents
        {
            public const string Delete = "REQUISITIONS.DOCUMENTS.DELETE";
            public const string Modify = "REQUISITIONS.DOCUMENTS.MODIFY";
            public const string View = "REQUISITIONS.DOCUMENTS.VIEW";
        }
        public const string Modify = "REQUISITIONS.MODIFY";
        public const string View = "REQUISITIONS.VIEW";
        public const string ViewAllDepartments = "REQUISITIONS.VIEW_ALL_DEPARTMENTS";
    }
    public static class Resources
    {
        public const string Allocate = "RESOURCES.ALLOCATE";
        public const string View = "RESOURCES.VIEW";
    }
    public static class Roles
    {
        public const string Create = "ROLES.CREATE";
        public const string Delete = "ROLES.DELETE";
        public const string Modify = "ROLES.MODIFY";
        public const string View = "ROLES.VIEW";
    }
    public static class Scrap
    {
        public const string Approve = "SCRAP.APPROVE";
        public const string Modify = "SCRAP.MODIFY";
        public const string View = "SCRAP.VIEW";
    }
    public static class Services
    {
        public const string Delete = "SERVICES.DELETE";
        public const string Modify = "SERVICES.MODIFY";
        public static class Transactions
        {
            public const string View = "SERVICES.TRANSACTIONS.VIEW";
        }
        public const string View = "SERVICES.VIEW";
    }
    public static class Staff
    {
        public const string Delete = "STAFF.DELETE";
        public const string Modify = "STAFF.MODIFY";
        public const string View = "STAFF.VIEW";
    }
    public static class Stockmovements
    {
        public const string Modify = "STOCKMOVEMENTS.MODIFY";
        public const string View = "STOCKMOVEMENTS.VIEW";
    }
    public static class Subsystems
    {
        public const string Delete = "SUBSYSTEMS.DELETE";
        public const string Modify = "SUBSYSTEMS.MODIFY";
        public const string View = "SUBSYSTEMS.VIEW";
    }
    public static class Tasks
    {
        public const string Assign = "TASKS.ASSIGN";
        public static class Comments
        {
            public const string Delete = "TASKS.COMMENTS.DELETE";
            public const string Modify = "TASKS.COMMENTS.MODIFY";
            public const string View = "TASKS.COMMENTS.VIEW";
        }
        public const string Delete = "TASKS.DELETE";
        public static class Dependencies
        {
            public const string Modify = "TASKS.DEPENDENCIES.MODIFY";
            public const string View = "TASKS.DEPENDENCIES.VIEW";
        }
        public const string Modify = "TASKS.MODIFY";
        public static class Subtasks
        {
            public const string Modify = "TASKS.SUBTASKS.MODIFY";
            public const string View = "TASKS.SUBTASKS.VIEW";
        }
        public const string View = "TASKS.VIEW";
    }
    public static class Timetracking
    {
        public const string LogAny = "TIMETRACKING.LOG_ANY";
        public const string LogOwn = "TIMETRACKING.LOG_OWN";
        public const string Reports = "TIMETRACKING.REPORTS";
        public const string View = "TIMETRACKING.VIEW";
    }
    public static class Tools
    {
        public const string Delete = "TOOLS.DELETE";
        public const string Modify = "TOOLS.MODIFY";
        public const string View = "TOOLS.VIEW";
    }
    public static class Users
    {
        public const string Modify = "USERS.MODIFY";
        public const string View = "USERS.VIEW";
    }
    public static class Vendorreturns
    {
        public const string Approve = "VENDORRETURNS.APPROVE";
        public const string Modify = "VENDORRETURNS.MODIFY";
        public const string View = "VENDORRETURNS.VIEW";
    }
    public static class Vendors
    {
        public static class Address
        {
            public const string Delete = "VENDORS.ADDRESS.DELETE";
            public const string Modify = "VENDORS.ADDRESS.MODIFY";
            public const string View = "VENDORS.ADDRESS.VIEW";
        }
        public static class Banks
        {
            public const string Delete = "VENDORS.BANKS.DELETE";
            public const string Modify = "VENDORS.BANKS.MODIFY";
            public const string View = "VENDORS.BANKS.VIEW";
        }
        public static class Contacts
        {
            public const string Delete = "VENDORS.CONTACTS.DELETE";
            public const string Modify = "VENDORS.CONTACTS.MODIFY";
            public const string View = "VENDORS.CONTACTS.VIEW";
        }
        public const string Delete = "VENDORS.DELETE";
        public static class Documents
        {
            public const string Delete = "VENDORS.DOCUMENTS.DELETE";
            public const string Modify = "VENDORS.DOCUMENTS.MODIFY";
            public const string View = "VENDORS.DOCUMENTS.VIEW";
        }
        public const string Modify = "VENDORS.MODIFY";
        public static class Parts
        {
            public const string Delete = "VENDORS.PARTS.DELETE";
            public const string Modify = "VENDORS.PARTS.MODIFY";
            public const string View = "VENDORS.PARTS.VIEW";
        }
        public const string View = "VENDORS.VIEW";
    }
    public static class Workorders
    {
        public const string Assignkit = "WORKORDERS.ASSIGNKIT";
        public const string Assignproduct = "WORKORDERS.ASSIGNPRODUCT";
        public const string Assigntechnician = "WORKORDERS.ASSIGNTECHNICIAN";
        public const string Delete = "WORKORDERS.DELETE";
        public static class Documents
        {
            public const string Delete = "WORKORDERS.DOCUMENTS.DELETE";
            public const string Modify = "WORKORDERS.DOCUMENTS.MODIFY";
            public const string View = "WORKORDERS.DOCUMENTS.VIEW";
        }
        public const string Modify = "WORKORDERS.MODIFY";
        public const string Print = "WORKORDERS.PRINT";
        public const string View = "WORKORDERS.VIEW";
    }

    /// <summary>All permission keys (for seeding / validation).</summary>
    public static readonly string[] All =
    [
        "ADDITIONALRECIPIENTS.DELETE",
        "ADDITIONALRECIPIENTS.MODIFY",
        "ADDITIONALRECIPIENTS.VIEW",
        "ApprovalsConfig.CREATE",
        "ApprovalsConfig.DELETE",
        "ApprovalsConfig.MODIFY",
        "ApprovalsConfig.VIEW",
        "ASSEMBLYLOCATIONS.DELETE",
        "ASSEMBLYLOCATIONS.MODIFY",
        "ASSEMBLYLOCATIONS.VIEW",
        "AUDIT.VIEW",
        "AUDIT.VIEW.REGULATED",
        "BINMANAGEMENT.DELETE",
        "BINMANAGEMENT.MODIFY",
        "BINMANAGEMENT.VIEW",
        "BOM.VIEW",
        "BULKUPLOAD.MODIFY",
        "BULKUPLOAD.VIEW",
        "COMPANIES.DELETE",
        "COMPANIES.DOCUMENTS.DELETE",
        "COMPANIES.DOCUMENTS.MODIFY",
        "COMPANIES.DOCUMENTS.VIEW",
        "COMPANIES.MODIFY",
        "COMPANIES.VIEW",
        "CONTACTS.DELETE",
        "CONTACTS.MODIFY",
        "CONTACTS.VIEW",
        "CUSTOMERS.DELETE",
        "CUSTOMERS.MODIFY",
        "CUSTOMERS.VIEW",
        "DASHBOARDS.CONFIGURE",
        "DASHBOARDS.VIEW",
        "DEPARTMENTS.DELETE",
        "DEPARTMENTS.MODIFY",
        "DEPARTMENTS.VIEW",
        "ECO.APPROVER",
        "ECO.DELETE",
        "ECO.DOCUMENTS.DELETE",
        "ECO.DOCUMENTS.MODIFY",
        "ECO.DOCUMENTS.VIEW",
        "ECO.EFFECTEDPARTS.DELETE",
        "ECO.EFFECTEDPARTS.MODIFY",
        "ECO.EFFECTEDPARTS.VIEW",
        "ECO.MODIFY",
        "ECO.VIEW",
        "EMAILLOGS.VIEW",
        "EMAILTEMPLATES.DELETE",
        "EMAILTEMPLATES.MODIFY",
        "EMAILTEMPLATES.VIEW",
        "FEATURES.DELETE",
        "FEATURES.MODIFY",
        "FEATURES.VIEW",
        "GANTT.MODIFY",
        "GANTT.VIEW",
        "GOODS.DELETE",
        "GOODS.MODIFY",
        "GOODS.TRANSACTIONS.VIEW",
        "GOODS.VIEW",
        "GOODSRECEIPTS.APPROVER",
        "GOODSRECEIPTS.DELETE",
        "GOODSRECEIPTS.DOCUMENTS.DELETE",
        "GOODSRECEIPTS.DOCUMENTS.MODIFY",
        "GOODSRECEIPTS.DOCUMENTS.VIEW",
        "GOODSRECEIPTS.MODIFY",
        "GOODSRECEIPTS.VIEW",
        "GUIDES.CLONE",
        "GUIDES.DELETE",
        "GUIDES.MODIFY",
        "GUIDES.PRINT",
        "GUIDES.PUBLISH",
        "GUIDES.VIEW",
        "ISSUES.DELETE",
        "ISSUES.MODIFY",
        "ISSUES.VIEW",
        "KANBAN.CONFIGURE",
        "KANBAN.MODIFY",
        "KANBAN.VIEW",
        "LOCATIONS.DELETE",
        "LOCATIONS.MODIFY",
        "LOCATIONS.VIEW",
        "MACHINES.DELETE",
        "MACHINES.MODIFY",
        "MACHINES.VIEW",
        "MATERIALKITS.ASSIGNWORKORDER",
        "MATERIALKITS.DELETE",
        "MATERIALKITS.MODIFY",
        "MATERIALKITS.VIEW",
        "NEWS.DELETE",
        "NEWS.MODIFY",
        "NEWS.VIEW",
        "ORGANIZATION.ADDRESS.DELETE",
        "ORGANIZATION.ADDRESS.MODIFY",
        "ORGANIZATION.ADDRESS.VIEW",
        "ORGANIZATION.DELETE",
        "ORGANIZATION.MODIFY",
        "ORGANIZATION.VIEW",
        "PARTLEVELS.DELETE",
        "PARTLEVELS.MODIFY",
        "PARTLEVELS.VIEW",
        "PARTNERS.DELETE",
        "PARTNERS.DOCUMENTS.DELETE",
        "PARTNERS.DOCUMENTS.MODIFY",
        "PARTNERS.DOCUMENTS.VIEW",
        "PARTNERS.MODIFY",
        "PARTNERS.VIEW",
        "PARTS.BOM.CLONE",
        "PARTS.BOM.DELETE",
        "PARTS.BOM.MODIFY",
        "PARTS.BOM.VIEW",
        "PARTS.DELETE",
        "PARTS.DOCUMENTS.DELETE",
        "PARTS.DOCUMENTS.MODIFY",
        "PARTS.DOCUMENTS.VIEW",
        "PARTS.INVENTORY.MODIFY",
        "PARTS.INVENTORY.PRICE",
        "PARTS.INVENTORY.VIEW",
        "PARTS.MODIFY",
        "PARTS.REVISE",
        "PARTS.TRANSACTIONS.VIEW",
        "PARTS.VIEW",
        "PARTS.WHEREUSED.VIEW",
        "PARTTYPECATEGORIES.DELETE",
        "PARTTYPECATEGORIES.MODIFY",
        "PARTTYPECATEGORIES.VIEW",
        "PARTTYPES.DELETE",
        "PARTTYPES.MODIFY",
        "PARTTYPES.VIEW",
        "PAYMENTTERMS.DELETE",
        "PAYMENTTERMS.MODIFY",
        "PAYMENTTERMS.VIEW",
        "PERMISSIONS.DELETE",
        "PERMISSIONS.MODIFY",
        "PERMISSIONS.VIEW",
        "PRODUCTS.BOM.DELETE",
        "PRODUCTS.BOM.MODIFY",
        "PRODUCTS.BOM.VIEW",
        "PRODUCTS.DELETE",
        "PRODUCTS.MODIFY",
        "PRODUCTS.VIEW",
        "PRODUCTS.WORKORDERS.VIEW",
        "PROGRAMS.DELETE",
        "PROGRAMS.LINKEDPROJECTS.VIEW",
        "PROGRAMS.MILESTONES.VIEW",
        "PROGRAMS.MODIFY",
        "PROGRAMS.VIEW",
        "PROJECTS.DELETE",
        "PROJECTS.MODIFY",
        "PROJECTS.VIEW",
        "PURCHASEORDERS.APPROVER",
        "PURCHASEORDERS.DELETE",
        "PURCHASEORDERS.DOCUMENTS.DELETE",
        "PURCHASEORDERS.DOCUMENTS.MODIFY",
        "PURCHASEORDERS.DOCUMENTS.VIEW",
        "PURCHASEORDERS.MODIFY",
        "PURCHASEORDERS.PRINT",
        "PURCHASEORDERS.VIEW",
        "PURCHASEORDERS.VIEW_ALL_DEPARTMENTS",
        "QUALITYCHECK.DELETE",
        "QUALITYCHECK.MODIFY",
        "QUALITYCHECK.VIEW",
        "QUALITYCHECKS.APPROVER",
        "QUALITYCHECKS.DELETE",
        "QUALITYCHECKS.DOCUMENTS.DELETE",
        "QUALITYCHECKS.DOCUMENTS.MODIFY",
        "QUALITYCHECKS.DOCUMENTS.VIEW",
        "QUALITYCHECKS.MODIFY",
        "QUALITYCHECKS.VIEW",
        "REPORTS.BOMCONSOLIDATED.VIEW",
        "REPORTS.DELETE",
        "REPORTS.MODIFY",
        "REPORTS.STOCKREPORT.VIEW",
        "REPORTS.VIEW",
        "REQUISITIONS.APPROVER",
        "REQUISITIONS.DELETE",
        "REQUISITIONS.DOCUMENTS.DELETE",
        "REQUISITIONS.DOCUMENTS.MODIFY",
        "REQUISITIONS.DOCUMENTS.VIEW",
        "REQUISITIONS.MODIFY",
        "REQUISITIONS.VIEW",
        "REQUISITIONS.VIEW_ALL_DEPARTMENTS",
        "RESOURCES.ALLOCATE",
        "RESOURCES.VIEW",
        "ROLES.CREATE",
        "ROLES.DELETE",
        "ROLES.MODIFY",
        "ROLES.VIEW",
        "SCRAP.APPROVE",
        "SCRAP.MODIFY",
        "SCRAP.VIEW",
        "SERVICES.DELETE",
        "SERVICES.MODIFY",
        "SERVICES.TRANSACTIONS.VIEW",
        "SERVICES.VIEW",
        "STAFF.DELETE",
        "STAFF.MODIFY",
        "STAFF.VIEW",
        "STOCKMOVEMENTS.MODIFY",
        "STOCKMOVEMENTS.VIEW",
        "SUBSYSTEMS.DELETE",
        "SUBSYSTEMS.MODIFY",
        "SUBSYSTEMS.VIEW",
        "TASKS.ASSIGN",
        "TASKS.COMMENTS.DELETE",
        "TASKS.COMMENTS.MODIFY",
        "TASKS.COMMENTS.VIEW",
        "TASKS.DELETE",
        "TASKS.DEPENDENCIES.MODIFY",
        "TASKS.DEPENDENCIES.VIEW",
        "TASKS.MODIFY",
        "TASKS.SUBTASKS.MODIFY",
        "TASKS.SUBTASKS.VIEW",
        "TASKS.VIEW",
        "TIMETRACKING.LOG_ANY",
        "TIMETRACKING.LOG_OWN",
        "TIMETRACKING.REPORTS",
        "TIMETRACKING.VIEW",
        "TOOLS.DELETE",
        "TOOLS.MODIFY",
        "TOOLS.VIEW",
        "USERS.MODIFY",
        "USERS.VIEW",
        "VENDORRETURNS.APPROVE",
        "VENDORRETURNS.MODIFY",
        "VENDORRETURNS.VIEW",
        "VENDORS.ADDRESS.DELETE",
        "VENDORS.ADDRESS.MODIFY",
        "VENDORS.ADDRESS.VIEW",
        "VENDORS.BANKS.DELETE",
        "VENDORS.BANKS.MODIFY",
        "VENDORS.BANKS.VIEW",
        "VENDORS.CONTACTS.DELETE",
        "VENDORS.CONTACTS.MODIFY",
        "VENDORS.CONTACTS.VIEW",
        "VENDORS.DELETE",
        "VENDORS.DOCUMENTS.DELETE",
        "VENDORS.DOCUMENTS.MODIFY",
        "VENDORS.DOCUMENTS.VIEW",
        "VENDORS.MODIFY",
        "VENDORS.PARTS.DELETE",
        "VENDORS.PARTS.MODIFY",
        "VENDORS.PARTS.VIEW",
        "VENDORS.VIEW",
        "WORKORDERS.ASSIGNKIT",
        "WORKORDERS.ASSIGNPRODUCT",
        "WORKORDERS.ASSIGNTECHNICIAN",
        "WORKORDERS.DELETE",
        "WORKORDERS.DOCUMENTS.DELETE",
        "WORKORDERS.DOCUMENTS.MODIFY",
        "WORKORDERS.DOCUMENTS.VIEW",
        "WORKORDERS.MODIFY",
        "WORKORDERS.PRINT",
        "WORKORDERS.VIEW",
    ];
}
