CREATE TABLE sc.company_part (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    part_id UUID NOT NULL,
    unit_price numeric(18,4),
    currency_id UUID,
    lead_time_days INTEGER,
    min_order_quantity INTEGER,
    order_multiple INTEGER,
    is_preferred BOOLEAN DEFAULT FALSE,
    valid_from DATE,
    valid_to DATE,
    vendor_part_number VARCHAR(225),
    manufacturer_part_number VARCHAR(225),
    notes TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,	
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(255) NOT NULL,
    updated_at TIMESTAMPTZ,
    updated_by VARCHAR(255),
    deleted_at TIMESTAMPTZ,
    deleted_by VARCHAR(255),
    FOREIGN KEY (company_id) REFERENCES sc.company(id) ON DELETE SET NULL,
    FOREIGN KEY (part_id) REFERENCES mes.part(id) ON DELETE SET NULL,
    FOREIGN KEY (currency_id) REFERENCES common.currency(id) ON DELETE SET NULL
);