CREATE TABLE sc.company (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    vendor_code VARCHAR(50) DEFAULT sc.generate_vendor_code(), 
    company_code VARCHAR(50) DEFAULT sc.generate_company_code(), 
    customer_code VARCHAR(50) DEFAULT sc.generate_customer_code(), 
    partner_code VARCHAR(50) DEFAULT sc.generate_partner_code(), 
    name VARCHAR(255) NOT NULL,
    is_vendor BOOLEAN,
    is_customer BOOLEAN,
    is_partner BOOLEAN,
    contact_name VARCHAR(100),
    phone_number VARCHAR(20),
    alternate_phone VARCHAR(20),
    website TEXT,
    tax_id VARCHAR(50),
    pan_number VARCHAR(10),
    currency_code CHAR(3),
    quality_score INT DEFAULT 0,
    category VARCHAR(100),
    department VARCHAR(100),
    payment_term_id UUID,
    currency_id UUID,
    logo_url TEXT,
    notes TEXT,
    total_orders INT DEFAULT 0,
    total_spent Float DEFAULT 0,
    avg_order_value Float DEFAULT 0,
    on_time_delivery_rate Float DEFAULT 0,
    member_since TIMESTAMPTZ,
    last_activity_date TIMESTAMPTZ,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(255) NOT NULL,
    updated_at TIMESTAMPTZ,
    updated_by VARCHAR(255),
    deleted_at TIMESTAMPTZ,
    deleted_by VARCHAR(255),
    FOREIGN KEY (payment_term_id) REFERENCES sc.payment_term(id) ON DELETE SET NULL,
    FOREIGN KEY (currency_id) REFERENCES common.currency(id) ON DELETE SET NULL,
    -- ✅ PAN number allowed only when is_vendor = TRUE
    CHECK (
        (is_vendor = TRUE AND (is_customer = FALSE OR is_customer IS NULL) AND (is_partner = FALSE OR is_partner IS NULL))
        OR (pan_number IS NULL)
    )
);