CREATE TABLE sc.grn_line_item (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    grn_id UUID NOT NULL,
    part_id UUID NOT NULL,	
    received_quantity INT,
    tracking_method VARCHAR(50) CHECK (tracking_method IS NULL OR tracking_method IN ('None', 'Batch', 'Serial')),
    tracking_id VARCHAR(255),
    manufacturing_date DATE,
    expiry_date DATE,
    qc_status VARCHAR(50) CHECK (qc_status IN ('Pending', 'Pass', 'Fail')) DEFAULT 'Pending',
    qc_date TIMESTAMPTZ,
    checked_by_id UUID,
    remark TEXT,
    disposition VARCHAR(50) CHECK (disposition IN ('Accepted', 'Return', 'Scrap', 'Rework', 'Quarantine')),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(255) NOT NULL,
    updated_at TIMESTAMPTZ,
    updated_by VARCHAR(255), 
    deleted_at TIMESTAMPTZ,
    deleted_by VARCHAR(255),
    FOREIGN KEY(grn_id) REFERENCES sc.goods_receipt_note(id) ON DELETE SET NULL,
    FOREIGN KEY(part_id) REFERENCES mes.part(id) ON DELETE SET NULL,
    FOREIGN KEY(checked_by_id) REFERENCES application."user"(id) ON DELETE SET NULL
);
