CREATE TABLE sc.goods_receipt_note (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    grn_number VARCHAR(255) NOT NULL DEFAULT sc.generate_grn_number(),
    purchase_order_id UUID,
    received_date DATE NOT NULL,
    received_by_id UUID,
    description TEXT,
    reference_number VARCHAR(255),
    invoice_number VARCHAR(255),
    invoice_date DATE,
    vendor_reference_id UUID,
    location_id UUID NOT NULL,
    vendor_id UUID,
    status VARCHAR(255) NOT NULL CHECK (status IN ('In Process', 'Quality Checked', 'Rejected')) DEFAULT 'In Process',
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(255) NOT NULL,
    updated_at TIMESTAMPTZ,
    updated_by VARCHAR(255),
    deleted_at TIMESTAMPTZ,
    deleted_by VARCHAR(255),
    FOREIGN KEY(purchase_order_id) REFERENCES sc.purchase_order(id) ON DELETE SET NULL,
    FOREIGN KEY(received_by_id) REFERENCES application."user"(id) ON DELETE SET NULL,
    FOREIGN KEY(vendor_reference_id) REFERENCES common.document(id) ON DELETE SET NULL,
    FOREIGN KEY(location_id) REFERENCES mes.location(id) ON DELETE SET NULL,
    FOREIGN KEY(vendor_id) REFERENCES sc.company(id) ON DELETE SET NULL
);