CREATE TABLE sc.inventory_transaction(
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    part_id UUID NOT NULL,
    from_location_id UUID,
    to_location_id UUID,
    transaction_type VARCHAR(255) NOT NULL CHECK (transaction_type IN ('Received', 'OnOrder', 'Consumed', 'Adjustment', 'Returned', 'Reserved', 'Defective', 'OnHold')),
    current_quantity INT,
    previous_quantity INT,
    transacted_quantity INT NOT NULL,
    reference_type VARCHAR(255),
    reference_id UUID,
    transaction_date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    notes TEXT,
    tracking_id VARCHAR(255),
    tracking_type VARCHAR(50),
    project_id UUID,
    assigned_user_id UUID,
    department VARCHAR(255),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(255) NOT NULL,
    updated_at TIMESTAMPTZ,
    updated_by VARCHAR(255),
    deleted_at TIMESTAMPTZ,
    deleted_by VARCHAR(255),
    FOREIGN KEY (assigned_user_id) REFERENCES application."user"(id) ON DELETE SET NULL,
    FOREIGN KEY (part_id) REFERENCES mes.part(id) ON DELETE SET NULL,
    FOREIGN KEY (from_location_id) REFERENCES mes.location(id) ON DELETE SET NULL,
    FOREIGN KEY (to_location_id) REFERENCES mes.location(id) ON DELETE SET NULL,
    FOREIGN KEY (project_id) REFERENCES pm.project(id) ON DELETE SET NULL
);