CREATE TABLE sc.inventory_stock(
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    part_id UUID NOT NULL,
    location_id UUID,
    bin_id UUID,
    qty_onhand INT NOT NULL,
    tracking_type VARCHAR(20),
    tracking_id VARCHAR(100),
    qty_available INT DEFAULT 0,
    qty_reserved INT DEFAULT 0,
    qty_consumed INT DEFAULT 0,
    qty_qc_pending INT DEFAULT 0,
    qty_qc_failed INT DEFAULT 0,
    qty_scrapped INT DEFAULT 0,
    qty_returned INT DEFAULT 0,
    opening_qty INT NOT NULL DEFAULT 0,
    opening_price NUMERIC(18,4) DEFAULT 0,
    project_id UUID,
    assigned_user_id UUID,
    department VARCHAR(255),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(255) NOT NULL,
    updated_at TIMESTAMPTZ,
    updated_by VARCHAR(255),
    deleted_at TIMESTAMPTZ,
    deleted_by VARCHAR(255),
    FOREIGN KEY (assigned_user_id) REFERENCES application."user"(id) ON DELETE SET NULL,
    FOREIGN KEY (part_id) REFERENCES mes.part(id) ON DELETE SET NULL,
    FOREIGN KEY (location_id) REFERENCES mes.location(id) ON DELETE SET NULL,
    FOREIGN KEY (bin_id) REFERENCES sc.bin_management(id) ON DELETE SET NULL,
    FOREIGN KEY (project_id) REFERENCES pm.project(id) ON DELETE SET NULL
);