CREATE TABLE sc.inventory_part (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    part_id UUID NOT NULL,
    sku_code VARCHAR(20),
    reorder_level INT NOT NULL DEFAULT 0,
    unit_price DECIMAL(18,2),
    qty_onhand INT NOT NULL DEFAULT 0,
    qty_reserved INT NOT NULL DEFAULT 0,
    qty_available INT GENERATED ALWAYS AS (qty_onhand - qty_reserved) STORED,
    consumed_quantity INT NOT NULL DEFAULT 0,
    qty_issued INT NOT NULL DEFAULT 0,
    qty_qc_pending INT NOT NULL DEFAULT 0,
    qty_scrapped INT NOT NULL DEFAULT 0,
    qty_qc_failed INT NOT NULL DEFAULT 0,
    qty_returned INT DEFAULT 0,
    location_id UUID,
    bin_id UUID,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(255) NOT NULL,
    updated_at TIMESTAMPTZ,
    updated_by VARCHAR(255),
    deleted_at TIMESTAMPTZ,
    deleted_by VARCHAR(255),
    FOREIGN KEY (part_id) REFERENCES mes.part(id) ON DELETE SET NULL,
    FOREIGN KEY (location_id) REFERENCES mes.location(id) ON DELETE SET NULL,
    FOREIGN KEY (bin_id) REFERENCES sc.bin_management(id) ON DELETE SET NULL
);