CREATE TABLE sc.purchase_order (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    number VARCHAR(255) NOT NULL DEFAULT sc.generate_purchase_order_number(),
	company_id UUID NOT NULL,
    project_id UUID, 
    buyer_id UUID, 
	supply_chain_lead_id UUID,  
	requisition_id UUID,  
    payment_term_id UUID,
    currency_id UUID,
	po_type VARCHAR(255),
    order_date DATE NOT NULL,
    actual_delivery_date DATE,
    expected_delivery_date DATE,
    tax_option VARCHAR(255),
    total_amount DECIMAL(18,2) NOT NULL,
	status VARCHAR(255) NOT NULL CHECK (status IN ('Draft', 'Submitted', 'Issued', 'Rejected', 'Partially Delivered', 'Delivered', 'Closed', 'Cancelled')) DEFAULT 'Draft',
	revision_history VARCHAR(255),
	round_off DECIMAL(18,2),
	quotation_reference_number VARCHAR(255),
	shipment_reference_number VARCHAR(255),
	billing_address_id UUID NOT NULL,
	delivery_address_id UUID,
	shipping_address_id UUID,
	vendor_billing_address_id UUID,
	vendor_billing_contact_id UUID,
	delivery_status VARCHAR(255) NOT NULL,
	quotation_reference_id UUID,
	po_terms TEXT,
	approved_by VARCHAR(255),
    approved_date TIMESTAMPTZ,
	rejected_by VARCHAR(255),
    rejected_date TIMESTAMPTZ,
	discount DECIMAL(18,2),
	discount_type VARCHAR(50),  -- Percentage, Amount
	department_id UUID,
	is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(255) NOT NULL,
    updated_at TIMESTAMPTZ,
    updated_by VARCHAR(255),
	deleted_at TIMESTAMPTZ,
    deleted_by VARCHAR(255),
    FOREIGN KEY(company_id) REFERENCES sc.company(id) ON DELETE SET NULL,		
	FOREIGN KEY(project_id) REFERENCES pm.project(id) ON DELETE SET NULL,			
	FOREIGN KEY(buyer_id) REFERENCES application."user"(id) ON DELETE SET NULL,	
	FOREIGN KEY(supply_chain_lead_id) REFERENCES application."user"(id) ON DELETE SET NULL,	
	FOREIGN KEY(requisition_id) REFERENCES sc.requisition(id) ON DELETE SET NULL,
	FOREIGN KEY(payment_term_id) REFERENCES sc.payment_term(id) ON DELETE SET NULL,	
	FOREIGN KEY(currency_id) REFERENCES common.currency(id) ON DELETE SET NULL,	
	FOREIGN KEY(billing_address_id) REFERENCES common.address(id) ON DELETE SET NULL,	
	FOREIGN KEY(delivery_address_id) REFERENCES common.address(id) ON DELETE SET NULL,	
	FOREIGN KEY(shipping_address_id) REFERENCES common.address(id) ON DELETE SET NULL,
	FOREIGN KEY(vendor_billing_address_id) REFERENCES common.address(id) ON DELETE SET NULL,
	FOREIGN KEY (vendor_billing_contact_id) REFERENCES common.contact(id) ON DELETE SET NULL,
	FOREIGN KEY(quotation_reference_id) REFERENCES common.document(id) ON DELETE SET NULL,
	FOREIGN KEY(department_id) REFERENCES common.department(id) ON DELETE SET NULL
);