CREATE TABLE sc.requisition  (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    req_number VARCHAR(255) NOT NULL DEFAULT sc.generate_req_number(),
    requested_by_id UUID NOT NULL,
    request_date DATE NOT NULL,
    title VARCHAR(255),
    project_id UUID,
    required_by_date DATE,
    justification TEXT,
    priority VARCHAR(255) NOT NULL, 
	status VARCHAR(255) NOT NULL CHECK (status IN ('Draft', 'Submitted', 'Approved', 'Rejected', 'Processing', 'Closed', 'Cancelled')) DEFAULT 'Draft',
    total_estimated_amount DECIMAL(18,2),
    approved_by VARCHAR(255),
    approved_date TIMESTAMPTZ,
    rejected_by VARCHAR(255),
    rejected_date TIMESTAMPTZ,
    approver_comment TEXT,
    department_id UUID,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(255) NOT NULL,
    updated_at TIMESTAMPTZ,
    updated_by VARCHAR(255),
    deleted_at TIMESTAMPTZ,
    deleted_by VARCHAR(255),
    FOREIGN KEY(requested_by_id) REFERENCES application."user"(id) ON DELETE SET NULL,
    FOREIGN KEY(project_id) REFERENCES pm.project(id) ON DELETE SET NULL,
    FOREIGN KEY(department_id) REFERENCES common.department(id) ON DELETE SET NULL
);