CREATE TABLE sc.stock_movement (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    movement_number varchar(255) UNIQUE NOT NULL,
    movement_type varchar(50) NOT NULL,
    movement_reason varchar(100) NULL,
    movement_date date NOT NULL,
    from_location_id uuid NULL,
    from_bin_id uuid NULL,
    to_location_id uuid NULL,
    to_bin_id uuid NULL,
    performed_by_id uuid NULL,
    work_order_id uuid NULL,
    reference_number varchar(255) NULL,
    notes text NULL,
    status varchar(50) NOT NULL DEFAULT 'Draft',
    expected_return_date DATE,
    project_date DATE,
    project_id uuid,
    sub_project_id uuid,
    department varchar(255),
    assigned_user_id uuid,
    department_id uuid,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by varchar(255) NOT NULL,
    updated_at timestamptz NULL,
    updated_by varchar(255) NULL,
    deleted_at timestamptz NULL,
    deleted_by varchar(255) NULL,
    issue_purpose varchar(255) NULL,
    company_id uuid NULL,
    sub_system varchar(100) NULL,
    classification varchar(50) NULL,
    platform_payload_sdr varchar(100) NULL,
    FOREIGN KEY (assigned_user_id) REFERENCES application."user"(id) ON DELETE SET NULL,
    FOREIGN KEY (department_id) REFERENCES common.department(id) ON DELETE SET NULL,
    FOREIGN KEY (project_id) REFERENCES pm.project(id) ON DELETE SET NULL,
    FOREIGN KEY (sub_project_id) REFERENCES pm.sub_project(id) ON DELETE SET NULL,
    FOREIGN KEY (from_location_id) REFERENCES mes.location(id) ON DELETE SET NULL,
    FOREIGN KEY (to_location_id) REFERENCES mes.location(id) ON DELETE SET NULL,
    FOREIGN KEY (from_bin_id) REFERENCES sc.bin_management(id) ON DELETE SET NULL,
    FOREIGN KEY (to_bin_id) REFERENCES sc.bin_management(id) ON DELETE SET NULL,
    FOREIGN KEY (work_order_id) REFERENCES mes.work_order(id) ON DELETE SET NULL,
    FOREIGN KEY (company_id) REFERENCES sc.company(id) ON DELETE SET NULL
);