CREATE TABLE sc.tender (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tender_number VARCHAR(50) UNIQUE NOT NULL,
    title VARCHAR(500) NOT NULL,
    description TEXT,
    status VARCHAR(50) DEFAULT 'Draft',
    requisition_id UUID,
    project_id UUID,
    publish_date DATE,
    closing_date DATE NOT NULL,
    approved_by VARCHAR(255),
    approved_date TIMESTAMPTZ,
    awarded_vendor_id UUID,
    awarded_date TIMESTAMPTZ,
    awarded_by VARCHAR(255),
    buyer_id UUID,
    terms TEXT,
    payment_term_id UUID,
    currency_id UUID,
    rejected_by VARCHAR(255),
    rejected_date TIMESTAMPTZ,
    approver_comment TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(255),
    updated_at TIMESTAMPTZ,
    updated_by VARCHAR(255),
    deleted_at TIMESTAMPTZ,
    deleted_by VARCHAR(255),
    FOREIGN KEY (requisition_id) REFERENCES sc.requisition(id) ON DELETE SET NULL,
    FOREIGN KEY (project_id) REFERENCES pm.project(id) ON DELETE SET NULL,
    FOREIGN KEY (awarded_vendor_id) REFERENCES sc.company(id) ON DELETE SET NULL,
    FOREIGN KEY (buyer_id) REFERENCES mes.user(id) ON DELETE SET NULL,
    FOREIGN KEY (payment_term_id) REFERENCES common.payment_term(id) ON DELETE SET NULL
);