CREATE TABLE sc.tender_quotation (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tender_id UUID NOT NULL,
    company_id UUID,
    quotation_number VARCHAR(100),
    quotation_date DATE NOT NULL,
    valid_until DATE,
    total_amount NUMERIC(18,4) NOT NULL DEFAULT 0,
    currency_id UUID,
    lead_time_days INTEGER,
    notes TEXT,
    terms_and_conditions TEXT,
    document_id UUID,
    is_selected BOOLEAN DEFAULT FALSE,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(255),
    updated_at TIMESTAMPTZ,
    updated_by VARCHAR(255),
    deleted_at TIMESTAMPTZ,
    deleted_by VARCHAR(255),
    FOREIGN KEY (tender_id) REFERENCES sc.tender(id) ON DELETE CASCADE,
    FOREIGN KEY (company_id) REFERENCES sc.company(id) ON DELETE SET NULL,
    FOREIGN KEY (currency_id) REFERENCES common.currency(id) ON DELETE SET NULL,
    FOREIGN KEY (document_id) REFERENCES common.document(id) ON DELETE SET NULL
);