CREATE TABLE sc.vendor_return_request (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    return_number VARCHAR(255) NOT NULL DEFAULT sc.generate_vendor_return_number(),
    vendor_id UUID NOT NULL,
    po_id UUID,
    grn_id UUID,
    wo_id UUID,
    return_date DATE,
    raised_by_id UUID,
    location_id UUID,
    reason TEXT,
    status VARCHAR(50) NOT NULL DEFAULT 'Draft' CHECK (status IN ('Draft','Submitted','Approved','Rejected','Shipped','Closed')),    
    approved_by VARCHAR(255),
    approved_date TIMESTAMPTZ,
	rejected_by VARCHAR(255),
    rejected_date TIMESTAMPTZ,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(255),
    updated_at TIMESTAMPTZ,
    updated_by VARCHAR(255),
    deleted_at TIMESTAMPTZ,
    deleted_by VARCHAR(255),
    FOREIGN KEY (vendor_id) REFERENCES sc.company(id) ON DELETE SET NULL,
    FOREIGN KEY (po_id) REFERENCES sc.purchase_order(id) ON DELETE SET NULL,
    FOREIGN KEY (grn_id) REFERENCES sc.goods_receipt_note(id) ON DELETE SET NULL,
    FOREIGN KEY (wo_id) REFERENCES mes.work_order(id) ON DELETE SET NULL,
    FOREIGN KEY (location_id) REFERENCES mes.location(id) ON DELETE SET NULL,
    FOREIGN KEY (raised_by_id) REFERENCES application.user(id) ON DELETE SET NULL
);