export const PERMISSIONS = {
  PROGRAMS: {
    VIEW: "PROGRAMS.VIEW",
    MODIFY: "PROGRAMS.MODIFY",
    DELETE: "PROGRAMS.DELETE",
    LINKEDPROJECTS: {
      VIEW: "PROGRAMS.LINKEDPROJECTS.VIEW",
    },
    MILESTONES: {
      VIEW: "PROGRAMS.MILESTONES.VIEW",
    },
  },
  PROJECTS: {
    VIEW: "PROJECTS.VIEW",
    MODIFY: "PROJECTS.MODIFY",
    DELETE: "PROJECTS.DELETE",
  },
  TASKS: {
    VIEW: "TASKS.VIEW",
    MODIFY: "TASKS.MODIFY",
    DELETE: "TASKS.DELETE",
    ASSIGN: "TASKS.ASSIGN",
    SUBTASKS: {
      VIEW: "TASKS.SUBTASKS.VIEW",
      MODIFY: "TASKS.SUBTASKS.MODIFY",
    },
    DEPENDENCIES: {
      VIEW: "TASKS.DEPENDENCIES.VIEW",
      MODIFY: "TASKS.DEPENDENCIES.MODIFY",
    },
    COMMENTS: {
      VIEW: "TASKS.COMMENTS.VIEW",
      MODIFY: "TASKS.COMMENTS.MODIFY",
      DELETE: "TASKS.COMMENTS.DELETE",
    },
  },
  TIMETRACKING: {
    VIEW: "TIMETRACKING.VIEW",
    LOG_OWN: "TIMETRACKING.LOG_OWN",
    LOG_ANY: "TIMETRACKING.LOG_ANY",
    REPORTS: "TIMETRACKING.REPORTS",
  },
  GANTT: {
    VIEW: "GANTT.VIEW",
    MODIFY: "GANTT.MODIFY",
  },
  KANBAN: {
    VIEW: "KANBAN.VIEW",
    MODIFY: "KANBAN.MODIFY",
    CONFIGURE: "KANBAN.CONFIGURE",
  },
  RESOURCES: {
    VIEW: "RESOURCES.VIEW",
    ALLOCATE: "RESOURCES.ALLOCATE",
  },
  DASHBOARDS: {
    VIEW: "DASHBOARDS.VIEW",
    CONFIGURE: "DASHBOARDS.CONFIGURE",
  },
  PARTS: {
    VIEW: "PARTS.VIEW",
    MODIFY: "PARTS.MODIFY",
    DELETE: "PARTS.DELETE",
    REVISE: "PARTS.REVISE",
    INVENTORY: {
      VIEW: "PARTS.INVENTORY.VIEW",
      MODIFY: "PARTS.INVENTORY.MODIFY",
      PRICE: "PARTS.INVENTORY.PRICE",
    },
    TRANSACTIONS: {
      VIEW: "PARTS.TRANSACTIONS.VIEW",
    },
    BOM: {
      VIEW: "PARTS.BOM.VIEW",
      MODIFY: "PARTS.BOM.MODIFY",
      DELETE: "PARTS.BOM.DELETE",
      CLONE: "PARTS.BOM.CLONE",
    },
    WHEREUSED: {
      VIEW: "PARTS.WHEREUSED.VIEW",
    },
    DOCUMENTS: {
      VIEW: "PARTS.DOCUMENTS.VIEW",
      MODIFY: "PARTS.DOCUMENTS.MODIFY",
      DELETE: "PARTS.DOCUMENTS.DELETE",
    },
  },
  BOM: {
    VIEW: "BOM.VIEW",
  },
  ECO: {
    VIEW: "ECO.VIEW",
    MODIFY: "ECO.MODIFY",
    DELETE: "ECO.DELETE",
    APPROVER: "ECO.APPROVER",
    EFFECTEDPARTS: {
      VIEW: "ECO.EFFECTEDPARTS.VIEW",
      MODIFY: "ECO.EFFECTEDPARTS.MODIFY",
      DELETE: "ECO.EFFECTEDPARTS.DELETE",
    },
    DOCUMENTS: {
      VIEW: "ECO.DOCUMENTS.VIEW",
      MODIFY: "ECO.DOCUMENTS.MODIFY",
      DELETE: "ECO.DOCUMENTS.DELETE",
    },
  },
  TOOLS: {
    VIEW: "TOOLS.VIEW",
    MODIFY: "TOOLS.MODIFY",
    DELETE: "TOOLS.DELETE",
  },
  MACHINES: {
    VIEW: "MACHINES.VIEW",
    MODIFY: "MACHINES.MODIFY",
    DELETE: "MACHINES.DELETE",
  },
  PRODUCTS: {
    VIEW: "PRODUCTS.VIEW",
    MODIFY: "PRODUCTS.MODIFY",
    DELETE: "PRODUCTS.DELETE",
    WORKORDERS: {
      VIEW: "PRODUCTS.WORKORDERS.VIEW",
    },
    BOM: {
      VIEW: "PRODUCTS.BOM.VIEW",
      MODIFY: "PRODUCTS.BOM.MODIFY",
      DELETE: "PRODUCTS.BOM.DELETE",
    },
  },
  GUIDES: {
    VIEW: "GUIDES.VIEW",
    MODIFY: "GUIDES.MODIFY",
    DELETE: "GUIDES.DELETE",
    PUBLISH: "GUIDES.PUBLISH",
    PRINT: "GUIDES.PRINT",
    CLONE: "GUIDES.CLONE",
  },
  WORKORDERS: {
    VIEW: "WORKORDERS.VIEW",
    MODIFY: "WORKORDERS.MODIFY",
    DELETE: "WORKORDERS.DELETE",
    ASSIGN_TECHNICIAN: "WORKORDERS.ASSIGNTECHNICIAN",
    ASSIGN_KIT: "WORKORDERS.ASSIGNKIT",
    ASSIGN_PRODUCT: "WORKORDERS.ASSIGNPRODUCT",
    PRINT: "WORKORDERS.PRINT",
    DOCUMENTS: {
      VIEW: "WORKORDERS.DOCUMENTS.VIEW",
      MODIFY: "WORKORDERS.DOCUMENTS.MODIFY",
      DELETE: "WORKORDERS.DOCUMENTS.DELETE",
    },
  },
  MATERIALKITS: {
    VIEW: "MATERIALKITS.VIEW",
    MODIFY: "MATERIALKITS.MODIFY",
    DELETE: "MATERIALKITS.DELETE",
    ASSIGN_WORKORDER: "MATERIALKITS.ASSIGNWORKORDER",
  },
  PURCHASEORDERS: {
    VIEW: "PURCHASEORDERS.VIEW",
    MODIFY: "PURCHASEORDERS.MODIFY",
    DELETE: "PURCHASEORDERS.DELETE",
    PRINT: "PURCHASEORDERS.PRINT",
    APPROVER: "PURCHASEORDERS.APPROVER",
    VIEW_ALL_DEPARTMENTS: "PURCHASEORDERS.VIEW_ALL_DEPARTMENTS",
    DOCUMENTS: {
      VIEW: "PURCHASEORDERS.DOCUMENTS.VIEW",
      MODIFY: "PURCHASEORDERS.DOCUMENTS.MODIFY",
      DELETE: "PURCHASEORDERS.DOCUMENTS.DELETE",
    },
  },
  GOODSRECEIPTS: {
    VIEW: "GOODSRECEIPTS.VIEW",
    MODIFY: "GOODSRECEIPTS.MODIFY",
    DELETE: "GOODSRECEIPTS.DELETE",
    APPROVER: "GOODSRECEIPTS.APPROVER",
    DOCUMENTS: {
      VIEW: "GOODSRECEIPTS.DOCUMENTS.VIEW",
      MODIFY: "GOODSRECEIPTS.DOCUMENTS.MODIFY",
      DELETE: "GOODSRECEIPTS.DOCUMENTS.DELETE",
    },
  },

  QUALITYCHECK: {
    VIEW: "QUALITYCHECK.VIEW",
    MODIFY: "QUALITYCHECK.MODIFY",
    DELETE: "QUALITYCHECK.DELETE",
  },
  QUALITYCHECKS: {
    VIEW: "QUALITYCHECKS.VIEW",
    MODIFY: "QUALITYCHECKS.MODIFY",
    DELETE: "QUALITYCHECKS.DELETE",
    APPROVER: "QUALITYCHECKS.APPROVER",
    DOCUMENTS: {
      VIEW: "QUALITYCHECKS.DOCUMENTS.VIEW",
      MODIFY: "QUALITYCHECKS.DOCUMENTS.MODIFY",
      DELETE: "QUALITYCHECKS.DOCUMENTS.DELETE",
    },
  },
  REQUISITIONS: {
    VIEW: "REQUISITIONS.VIEW",
    MODIFY: "REQUISITIONS.MODIFY",
    DELETE: "REQUISITIONS.DELETE",
    APPROVER: "REQUISITIONS.APPROVER",
    VIEW_ALL_DEPARTMENTS: "REQUISITIONS.VIEW_ALL_DEPARTMENTS",
    DOCUMENTS: {
      VIEW: "REQUISITIONS.DOCUMENTS.VIEW",
      MODIFY: "REQUISITIONS.DOCUMENTS.MODIFY",
      DELETE: "REQUISITIONS.DOCUMENTS.DELETE",
    },
  },
  VENDORS: {
    VIEW: "VENDORS.VIEW",
    MODIFY: "VENDORS.MODIFY",
    DELETE: "VENDORS.DELETE",
    ADDRESS: {
      VIEW: "VENDORS.ADDRESS.VIEW",
      MODIFY: "VENDORS.ADDRESS.MODIFY",
      DELETE: "VENDORS.ADDRESS.DELETE",
    },
    CONTACTS: {
      VIEW: "VENDORS.CONTACTS.VIEW",
      MODIFY: "VENDORS.CONTACTS.MODIFY",
      DELETE: "VENDORS.CONTACTS.DELETE",
    },
    BANKS: {
      VIEW: "VENDORS.BANKS.VIEW",
      MODIFY: "VENDORS.BANKS.MODIFY",
      DELETE: "VENDORS.BANKS.DELETE",
    },
    PARTS: {
      VIEW: "VENDORS.PARTS.VIEW",
      MODIFY: "VENDORS.PARTS.MODIFY",
      DELETE: "VENDORS.PARTS.DELETE",
    },
    DOCUMENTS: {
      VIEW: "VENDORS.DOCUMENTS.VIEW",
      MODIFY: "VENDORS.DOCUMENTS.MODIFY",
      DELETE: "VENDORS.DOCUMENTS.DELETE",
    },
  },

  COMPANIES: {
    VIEW: "COMPANIES.VIEW",
    MODIFY: "COMPANIES.MODIFY",
    DELETE: "COMPANIES.DELETE",

    DOCUMENTS: {
      VIEW: "COMPANIES.DOCUMENTS.VIEW",
      MODIFY: "COMPANIES.DOCUMENTS.MODIFY",
      DELETE: "COMPANIES.DOCUMENTS.DELETE",
    },
  },
  CUSTOMERS: {
    VIEW: "CUSTOMERS.VIEW",
    MODIFY: "CUSTOMERS.MODIFY",
    DELETE: "CUSTOMERS.DELETE",
  },

  PARTNERS: {
    VIEW: "PARTNERS.VIEW",
    MODIFY: "PARTNERS.MODIFY",
    DELETE: "PARTNERS.DELETE",

    DOCUMENTS: {
      VIEW: "PARTNERS.DOCUMENTS.VIEW",
      MODIFY: "PARTNERS.DOCUMENTS.MODIFY",
      DELETE: "PARTNERS.DOCUMENTS.DELETE",
    },
  },

  CONTACTS: {
    VIEW: "CONTACTS.VIEW",
    MODIFY: "CONTACTS.MODIFY",
    DELETE: "CONTACTS.DELETE",
  },
  GOODS: {
    VIEW: "GOODS.VIEW",
    MODIFY: "GOODS.MODIFY",
    DELETE: "GOODS.DELETE",
    TRANSACTIONS: {
      VIEW: "GOODS.TRANSACTIONS.VIEW",
    },
  },
  SERVICES: {
    VIEW: "SERVICES.VIEW",
    MODIFY: "SERVICES.MODIFY",
    DELETE: "SERVICES.DELETE",
    TRANSACTIONS: {
      VIEW: "SERVICES.TRANSACTIONS.VIEW",
    },
  },
  STOCKMOVEMENTS: {
    VIEW: "STOCKMOVEMENTS.VIEW",
    MODIFY: "STOCKMOVEMENTS.MODIFY",
  },
  VENDORRETURNS: {
    VIEW: "VENDORRETURNS.VIEW",
    MODIFY: "VENDORRETURNS.MODIFY",
    APPROVE: "VENDORRETURNS.APPROVE",
  },
  SCRAP: {
    VIEW: "SCRAP.VIEW",
    MODIFY: "SCRAP.MODIFY",
    APPROVE: "SCRAP.APPROVE",
  },
  PAYMENTTERMS: {
    VIEW: "PAYMENTTERMS.VIEW",
    MODIFY: "PAYMENTTERMS.MODIFY",
    DELETE: "PAYMENTTERMS.DELETE",
  },
  EMAILLOGS: {
    VIEW: "EMAILLOGS.VIEW",
  },
  BINMANAGEMENT: {
    VIEW: "BINMANAGEMENT.VIEW",
    MODIFY: "BINMANAGEMENT.MODIFY",
    DELETE: "BINMANAGEMENT.DELETE",
  },
  PARTTYPES: {
    VIEW: "PARTTYPES.VIEW",
    MODIFY: "PARTTYPES.MODIFY",
    DELETE: "PARTTYPES.DELETE",
  },
  PARTTYPECATEGORIES: {
    VIEW: "PARTTYPECATEGORIES.VIEW",
    MODIFY: "PARTTYPECATEGORIES.MODIFY",
    DELETE: "PARTTYPECATEGORIES.DELETE",
  },
  SUBSYSTEMS: {
    VIEW: "SUBSYSTEMS.VIEW",
    MODIFY: "SUBSYSTEMS.MODIFY",
    DELETE: "SUBSYSTEMS.DELETE",
  },
  PARTLEVELS: {
    VIEW: "PARTLEVELS.VIEW",
    MODIFY: "PARTLEVELS.MODIFY",
    DELETE: "PARTLEVELS.DELETE",
  },
  BULKUPLOAD: {
    VIEW: "BULKUPLOAD.VIEW",
    MODIFY: "BULKUPLOAD.MODIFY",
  },
  ASSEMBLYLOCATIONS: {
    VIEW: "ASSEMBLYLOCATIONS.VIEW",
    MODIFY: "ASSEMBLYLOCATIONS.MODIFY",
    DELETE: "ASSEMBLYLOCATIONS.DELETE",
  },
  LOCATIONS: {
    VIEW: "LOCATIONS.VIEW",
    MODIFY: "LOCATIONS.MODIFY",
    DELETE: "LOCATIONS.DELETE",
  },
  ISSUES: {
    VIEW: "ISSUES.VIEW",
    MODIFY: "ISSUES.MODIFY",
    DELETE: "ISSUES.DELETE",
  },
  NEWS: {
    VIEW: "NEWS.VIEW",
    MODIFY: "NEWS.MODIFY",
    DELETE: "NEWS.DELETE",
  },
  REPORTS: {
    VIEW: "REPORTS.VIEW",
    MODIFY: "REPORTS.MODIFY",
    DELETE: "REPORTS.DELETE",
    BOMCONSOLIDATED: {
      VIEW: "REPORTS.BOMCONSOLIDATED.VIEW",
    },
  },
  USERS: {
    VIEW: "USERS.VIEW",
    MODIFY: "USERS.MODIFY",
  },
  DEPARTMENTS: {
    VIEW: "DEPARTMENTS.VIEW",
    MODIFY: "DEPARTMENTS.MODIFY",
    DELETE: "DEPARTMENTS.DELETE",
  },
  ROLES: {
    VIEW: "ROLES.VIEW",
    CREATE: "ROLES.CREATE",
    MODIFY: "ROLES.MODIFY",
    DELETE: "ROLES.DELETE",
  },
  ApprovalsConfig: {
    VIEW: "ApprovalsConfig.VIEW",
    CREATE: "ApprovalsConfig.CREATE",
    MODIFY: "ApprovalsConfig.MODIFY",
    DELETE: "ApprovalsConfig.DELETE",
  },
  PERMISSIONS: {
    VIEW: "PERMISSIONS.VIEW",
    MODIFY: "PERMISSIONS.MODIFY",
    DELETE: "PERMISSIONS.DELETE",
  },
  ORGANIZATION: {
    VIEW: "ORGANIZATION.VIEW",
    MODIFY: "ORGANIZATION.MODIFY",
    DELETE: "ORGANIZATION.DELETE",
    ADDRESS: {
      VIEW: "ORGANIZATION.ADDRESS.VIEW",
      MODIFY: "ORGANIZATION.ADDRESS.MODIFY",
      DELETE: "ORGANIZATION.ADDRESS.DELETE",
    },
  },
  STAFF: {
    VIEW: "STAFF.VIEW",
    MODIFY: "STAFF.MODIFY",
    DELETE: "STAFF.DELETE",
  },
  FEATURES: {
    VIEW: "FEATURES.VIEW",
    MODIFY: "FEATURES.MODIFY",
    DELETE: "FEATURES.DELETE",
  },
  EMAILTEMPLATES: {
    VIEW: "EMAILTEMPLATES.VIEW",
    MODIFY: "EMAILTEMPLATES.MODIFY",
    DELETE: "EMAILTEMPLATES.DELETE",
  },
  ADDITIONALRECIPIENTS: {
    VIEW: "ADDITIONALRECIPIENTS.VIEW",
    MODIFY: "ADDITIONALRECIPIENTS.MODIFY",
    DELETE: "ADDITIONALRECIPIENTS.DELETE",
  },
};
